/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-07 19:02:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.cc.model.Usuario;

public final class formAlterarSenha_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1631030311270L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.cc.model.Usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/estilo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#dadosUsuario{\r\n");
      out.write("	color: yellow;\r\n");
      out.write("	padding: 16px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("#dadosUsuario a{\r\n");
      out.write("	color: black;\r\n");
      out.write("	background-color:#fff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("	padding:2px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    font-size: 9px;\r\n");
      out.write("}\r\n");
      out.write("#dadosUsuario a:hover{\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	color: yellow;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<ul>\r\n");
      out.write("	  \r\n");
      out.write("	   ");

        Usuario usuario = (Usuario) request.getSession().getAttribute("usuario");
    	boolean verLista = false;
    	if(usuario != null){
    		verLista = true;
    	
      out.write("\r\n");
      out.write("    	<span id=\"dadosUsuario\"> <a href=\"loginservlet?acao=sair\"><b>Logout</b></a></span>\r\n");
      out.write("    	<span id=\"dadosUsuario\">Bem Vindo: ");
      out.print(usuario.getEmail());
      out.write("</span>\r\n");
      out.write("        <li><a href=\"index.jsp\"><b>Home</b></a></li>\r\n");
      out.write("        <li><a href=\"formGerenciaPainel.jsp\"><b>Gerenciar Painel</b></a>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(usuario.getPerfil().equals("administrador")){ 
      out.write("    \r\n");
      out.write("        <li><a href=\"formManterUsuario.jsp\"><b>Manter Usuário</b></a></li>\r\n");
      out.write("        ");
}else{
      out.write("\r\n");
      out.write("        <li><a href=\"formAlterarSenha.jsp\"><b>Alterar Senha</b></a></li>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("      ");

    	}else{
    	
      out.write("\r\n");
      out.write("   		<li></li>\r\n");
      out.write("    	");
	
    	} 
    	
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');

	if (usuario == null) {
		response.sendRedirect("formLogin.jsp");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<br>\r\n");
      out.write("		<h2>Alterar Senha</h2>\r\n");
      out.write("		<form name=\"form-alterarSenha\" id=\"form-alterarSenha\" action=\"AlterarSenhaServlet\" method=\"Post\">\r\n");
      out.write("		<div class=\"alert alert-primary col-md-6\" role=\"alert\"  id=\"msg\"></div>\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group col-md-6\">\r\n");
      out.write("					<label for=\"senhaAtual\">Senha Atual:</label> <input type=\"password\"\r\n");
      out.write("						class=\"form-control\" id=\"senhaAtual\" placeholder=\"Senha atual.\"\r\n");
      out.write("						name=\"senhaAtual\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group col-md-6\">\r\n");
      out.write("					<label for=\"novaSenha\">Nova Senha:</label> <input type=\"password\"\r\n");
      out.write("						class=\"form-control\" id=\"novaSenha\" placeholder=\"Nova senha.\" name=\"novaSenha\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group col-md-6\">\r\n");
      out.write("					<label for=\"confirmarSenha\">Confirmar Senha:</label> <input type=\"password\"\r\n");
      out.write("						class=\"form-control\" id=\"confirmarSenha\" placeholder=\"Confirmar senha.\" name=\"confirmarSenha\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"button\" class=\"btn btn-primary\" value=\"Gravar\" onclick=\"alterarSenha()\">\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function alterarSenha() {\r\n");
      out.write("			var senhaAtual = document.getElementById(\"senhaAtual\").value;\r\n");
      out.write("			var novaSenha = document.getElementById(\"novaSenha\").value;\r\n");
      out.write("			var confirmarSenha = document.getElementById(\"confirmarSenha\").value;\r\n");
      out.write("\r\n");
      out.write("			var parametros = \"senhaAtual=\" + senhaAtual;\r\n");
      out.write("			parametros += \"&novaSenha=\" + novaSenha;\r\n");
      out.write("			parametros += \"&confirmarSenha=\" + confirmarSenha;\r\n");
      out.write("			acessarApi(parametros);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function acessarApi(parametros) {\r\n");
      out.write("			const api = new XMLHttpRequest();\r\n");
      out.write("			api.open(\"POST\",\r\n");
      out.write("					\"http://localhost:8080/centro_cirurgico_web/AlterarSenhaServlet\");\r\n");
      out.write("			api.setRequestHeader(\"Content-type\",\r\n");
      out.write("					\"application/x-www-form-urlencoded\");\r\n");
      out.write("			api.send(parametros);\r\n");
      out.write("			api.onload = function() {\r\n");
      out.write("				document.getElementById(\"msg\").innerHTML = this.responseText;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
