/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-08 17:59:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.cc.dao.UsuarioDao;
import org.cc.model.Usuario;
import java.util.List;
import org.cc.model.Usuario;
import org.cc.dao.UsuarioDao;

public final class formManterUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/formListaUsuario.jsp", Long.valueOf(1631116841521L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1631030311270L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.cc.model.Usuario");
    _jspx_imports_classes.add("org.cc.dao.UsuarioDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Manter Usuário</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/estilo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#dadosUsuario{\r\n");
      out.write("	color: yellow;\r\n");
      out.write("	padding: 16px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("#dadosUsuario a{\r\n");
      out.write("	color: black;\r\n");
      out.write("	background-color:#fff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("	padding:2px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    font-size: 9px;\r\n");
      out.write("}\r\n");
      out.write("#dadosUsuario a:hover{\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	color: yellow;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<ul>\r\n");
      out.write("	  \r\n");
      out.write("	   ");

        Usuario usuario = (Usuario) request.getSession().getAttribute("usuario");
    	boolean verLista = false;
    	if(usuario != null){
    		verLista = true;
    	
      out.write("\r\n");
      out.write("    	<span id=\"dadosUsuario\"> <a href=\"loginservlet?acao=sair\"><b>Logout</b></a></span>\r\n");
      out.write("    	<span id=\"dadosUsuario\">Bem Vindo: ");
      out.print(usuario.getEmail());
      out.write("</span>\r\n");
      out.write("        <li><a href=\"index.jsp\"><b>Home</b></a></li>\r\n");
      out.write("        <li><a href=\"formGerenciaPainel.jsp\"><b>Gerenciar Painel</b></a>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(usuario.getPerfil().equals("administrador")){ 
      out.write("    \r\n");
      out.write("        <li><a href=\"formManterUsuario.jsp\"><b>Manter Usuário</b></a></li>\r\n");
      out.write("        ");
}else{
      out.write("\r\n");
      out.write("        <li><a href=\"formAlterarSenha.jsp\"><b>Alterar Senha</b></a></li>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("      ");

    	}else{
    	
      out.write("\r\n");
      out.write("   		<li></li>\r\n");
      out.write("    	");
	
    	} 
    	
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	if (usuario == null) {
		response.sendRedirect("formLogin.jsp");
	}	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	Usuario u = new Usuario();

	try {
		int id = Integer.parseInt(request.getParameter("id"));
		UsuarioDao dao = new UsuarioDao();
		u = dao.getUsuario(id);
	} catch (Exception e) {

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<br>\r\n");
      out.write("		<h2>Manter Usuário</h2>\r\n");
      out.write("		<form name=\"form-usuario\" id=\"form-usuario\"\r\n");
      out.write("			action=\"ManterUsuarioServlet\" method=\"Post\">\r\n");
      out.write("		<div class=\"alert alert-primary col-md-6\" role=\"alert\"  id=\"msg\"></div>\r\n");
      out.write("			<input type=\"hidden\" id=\"id\" name=\"id\" value=\"");
      out.print(u.getId());
      out.write("\">\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group col-md-6\">\r\n");
      out.write("					<label for=\"email\">E-mail:</label> <input type=\"email\"\r\n");
      out.write("						class=\"form-control\" id=\"email\" placeholder=\"E-mail do usuário.\"\r\n");
      out.write("						name=\"email\" value=\"");
      out.print(u.getEmail());
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group col-md-6\">\r\n");
      out.write("					<label for=\"senha\">Senha:</label> <input type=\"password\"\r\n");
      out.write("						class=\"form-control\" id=\"senha\" placeholder=\"Senha do usuário.\"\r\n");
      out.write("						name=\"senha\" value=\"");
      out.print(u.getSenha());
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			");

			if (usuario != null && usuario.getPerfil().equals("administrador")) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group col-md-6\">\r\n");
      out.write("					<label for=\"Perfil\">Perfil:</label>\r\n");
      out.write("					<div class=\"form-control borda\">\r\n");
      out.write("						<input type=\"radio\" id=\"administrador\" name=\"perfil\"\r\n");
      out.write("							value=\"administrador\" checked=\"checked\"><label\r\n");
      out.write("							for=\"administrador\"> Administrador</label> <input type=\"radio\"\r\n");
      out.write("							class=\"espacamento\" id=\"operador\" name=\"perfil\" value=\"operador\"><label\r\n");
      out.write("							for=\"operador\"> Operador</label> <input type=\"radio\"\r\n");
      out.write("							class=\"espacamento\" id=\"estagiario\" name=\"perfil\"\r\n");
      out.write("							value=\"estagiario\"><label for=\"estagiario\">\r\n");
      out.write("							Estagiário</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group col-md-6\">\r\n");
      out.write("					<label for=\"Perfil\">Perfil:</label>\r\n");
      out.write("					<div class=\"form-control borda\"  >\r\n");
      out.write("						<input type=\"radio\" id=\"administrador\" name=\"perfil\"\r\n");
      out.write("							value=\"administrador\" disabled=\"disabled\"><label\r\n");
      out.write("							for=\"administrador\"> Administrador</label> <input type=\"radio\"\r\n");
      out.write("							class=\"espacamento\" id=\"operador\" name=\"perfil\" value=\"operador\"\r\n");
      out.write("							disabled=\"disabled\"><label for=\"operador\">\r\n");
      out.write("							Operador</label> <input type=\"radio\" class=\"espacamento\" id=\"estagiario\"\r\n");
      out.write("							name=\"perfil\" value=\"estagiario\" disabled=\"disabled\"><label\r\n");
      out.write("							for=\"estagiario\"> Estagiário</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("			<input type=\"button\" class=\"btn btn-primary\" value=\"Gravar\" onclick=\"cadastrarUsuario()\">\r\n");
      out.write("			");

			if (usuario == null) {
			
      out.write("\r\n");
      out.write("			<a href=\"formLogin.jsp\" type=\"submit\" class=\"btn btn-secondary\"\r\n");
      out.write("				value=\"voltar\">Voltar</a>\r\n");
      out.write("\r\n");
      out.write("			");

			} else if (u.getId() > 0) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<input type=\"button\" class=\"btn btn-danger\" value=\"Apagar\" onclick=\"excluirUsuario(");
      out.print(u.getId());
      out.write(")\">\r\n");
      out.write("				\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("			<input type=\"reset\" class=\"btn btn-danger\" value=\"Limpar\">\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

			if (usuario != null) {
			
      out.write("\r\n");
      out.write("			<a href=\"formManterUsuario.jsp\" type=\"submit\" class=\"btn btn-success\" id=\"espacamento\" value=\"Cadastrar\">Novo</a>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("		<br>\r\n");
      out.write("		\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("		function cadastrarUsuario() {\r\n");
      out.write("			var id = document.querySelector(\"#id\").value;\r\n");
      out.write("			var email = document.querySelector(\"#email\").value;\r\n");
      out.write("			var senha = document.querySelector(\"#senha\").value;\r\n");
      out.write("			var perfil = document.querySelector('[name=\"perfil\"]:checked').value;\r\n");
      out.write("\r\n");
      out.write("			var out = \"\";\r\n");
      out.write("			out += \"id=$id&email=$email&senha=$senha&perfil=$perfil\";\r\n");
      out.write("			out = out.replace(\"$id\",id)\r\n");
      out.write("			out = out.replace(\"$email\",email)\r\n");
      out.write("			out = out.replace(\"$senha\",senha)\r\n");
      out.write("			out = out.replace(\"$perfil\",perfil);\r\n");
      out.write("			acessarApiServlet(out);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function excluirUsuario(id){\r\n");
      out.write("			if(confirm('Deseja excluir esse registro?')){\r\n");
      out.write("				acessarApiServlet(\"id=\"+id+\"&acao=excluir\");\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function acessarApiServlet(parametros) {\r\n");
      out.write("			const api = new XMLHttpRequest();\r\n");
      out.write("			api.open(\"POST\", \"ManterUsuarioServlet?\"+parametros);\r\n");
      out.write("			api.send();\r\n");
      out.write("			api.onload = function() {\r\n");
      out.write("				var dados = this.responseText;\r\n");
      out.write("				dados = JSON.parse(dados);\r\n");
      out.write("				document.querySelector(\"#msg\").innerHTML = dados.msg;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var lsPerfil = document.getElementsByName(\"perfil\");\r\n");
      out.write("		for (i in lsPerfil) {\r\n");
      out.write("			if (lsPerfil[i].value == '");
      out.print(u.getPerfil());
      out.write("') {\r\n");
      out.write("					lsPerfil[i].setAttribute('checked', 'checked');\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("		");

		if (usuario != null && usuario.getPerfil().equals("administrador")) {
		
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Listar Usuários</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/estilo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<h2>Listar Usuários</h2>\r\n");
      out.write("\r\n");
      out.write("<table class=\"table table-success table-striped table-hover\">\r\n");
      out.write("	<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>ID</th>\r\n");
      out.write("			<th>Login</th>\r\n");
      out.write("			<th>Perfil</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</thead>\r\n");
      out.write("		");

		UsuarioDao objUDao = new UsuarioDao();
		List<Usuario> ls = objUDao.listarUsuario();

		if (ls.size() > 0) {
			for (Usuario us : ls) {
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<tr\r\n");
      out.write("			onclick=\"window.location.href = 'formManterUsuario.jsp?id=");
      out.print(us.getId());
      out.write("'\" >\r\n");
      out.write("			<td>");
      out.print(us.getId());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(us.getEmail());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(us.getPerfil());
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"3\" style=\"text-align: center\">\"Nenhuma informação\r\n");
      out.write("				encontrada!\"</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
