/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-07 15:59:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.cc.model.Usuario;

public final class formGerenciaPainel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1631030311270L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.cc.model.Usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Gerenciar Painel Pacientes</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/estilo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#dadosUsuario{\r\n");
      out.write("	color: yellow;\r\n");
      out.write("	padding: 16px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("#dadosUsuario a{\r\n");
      out.write("	color: black;\r\n");
      out.write("	background-color:#fff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("	padding:2px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    font-size: 9px;\r\n");
      out.write("}\r\n");
      out.write("#dadosUsuario a:hover{\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	color: yellow;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<ul>\r\n");
      out.write("	  \r\n");
      out.write("	   ");

        Usuario usuario = (Usuario) request.getSession().getAttribute("usuario");
    	boolean verLista = false;
    	if(usuario != null){
    		verLista = true;
    	
      out.write("\r\n");
      out.write("    	<span id=\"dadosUsuario\"> <a href=\"loginservlet?acao=sair\"><b>Logout</b></a></span>\r\n");
      out.write("    	<span id=\"dadosUsuario\">Bem Vindo: ");
      out.print(usuario.getEmail());
      out.write("</span>\r\n");
      out.write("        <li><a href=\"index.jsp\"><b>Home</b></a></li>\r\n");
      out.write("        <li><a href=\"formGerenciaPainel.jsp\"><b>Gerenciar Painel</b></a>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(usuario.getPerfil().equals("administrador")){ 
      out.write("    \r\n");
      out.write("        <li><a href=\"formManterUsuario.jsp\"><b>Manter Usuário</b></a></li>\r\n");
      out.write("        ");
}else{
      out.write("\r\n");
      out.write("        <li><a href=\"formAlterarSenha.jsp\"><b>Alterar Senha</b></a></li>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("      ");

    	}else{
    	
      out.write("\r\n");
      out.write("   		<li></li>\r\n");
      out.write("    	");
	
    	} 
    	
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("		var pacientes = localStorage.getItem('ls-tabela');\r\n");
      out.write("		\r\n");
      out.write("		if(pacientes == null){\r\n");
      out.write("			pacientes = [];\r\n");
      out.write("		}else{\r\n");
      out.write("			pacientes = JSON.parse(pacientes);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function gravar() {\r\n");
      out.write("\r\n");
      out.write("			var vId = document.getElementById(\"id\").value;\r\n");
      out.write("			var vNome = document.getElementById(\"nome\").value.toUpperCase();	\r\n");
      out.write("			if (vNome == '') {\r\n");
      out.write("				alert('O Nome do Paciente é obrigatório.');\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var vStatus = document.getElementById(\"status\").value;\r\n");
      out.write("			var vLocal = document.getElementById(\"local\").value;\r\n");
      out.write("			var vIniPrevisto = document.getElementById(\"inicio-previsto\").value;\r\n");
      out.write("			var vIniCirurgia = document.getElementById(\"inicio-cirurgia\").value;\r\n");
      out.write("			var vFimCirurgia = document.getElementById(\"fim-cirurgia\").value;\r\n");
      out.write("			var vSaidaPrev = document.getElementById(\"saida-previsto\").value;\r\n");
      out.write("\r\n");
      out.write("			if (vLocal != '') {\r\n");
      out.write("				vLocal = '(' + vLocal + ')';\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var save = confirm(\"Deseja Salvar as alterações?\");\r\n");
      out.write("			if (save) {\r\n");
      out.write("\r\n");
      out.write("				var paciente = {\r\n");
      out.write("					nome : vNome,\r\n");
      out.write("					status : vStatus,\r\n");
      out.write("					local : vLocal,\r\n");
      out.write("					iniPrevisto : vIniPrevisto,\r\n");
      out.write("					iniCirurgia : vIniCirurgia,\r\n");
      out.write("					fimCirurgia : vFimCirurgia,\r\n");
      out.write("					saidaPrev : vSaidaPrev,\r\n");
      out.write("				};\r\n");
      out.write("\r\n");
      out.write("				if (vId == '') {\r\n");
      out.write("					pacientes.splice(pacientes.length, 0, paciente);\r\n");
      out.write("				} else {\r\n");
      out.write("					pacientes[vId] = paciente;\r\n");
      out.write("				}\r\n");
      out.write("				atualizarTabela();\r\n");
      out.write("				limpaForm();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function preparaEdicao(id) {\r\n");
      out.write("			var p = pacientes[id];\r\n");
      out.write("			document.getElementById(\"id\").value = id;\r\n");
      out.write("			document.getElementById(\"nome\").value = p.nome;\r\n");
      out.write("			document.getElementById(\"status\").value = p.status;\r\n");
      out.write("			document.getElementById(\"local\").value = p.local.replace(\"(\",\"\").replace(\")\",\"\");\r\n");
      out.write("			document.getElementById(\"inicio-previsto\").value = p.iniPrevisto;\r\n");
      out.write("			document.getElementById(\"inicio-cirurgia\").value = p.iniCirurgia;\r\n");
      out.write("			document.getElementById(\"fim-cirurgia\").value = p.fimCirurgia;\r\n");
      out.write("			document.getElementById(\"saida-previsto\").value = p.saidaPrev;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function status(status) {\r\n");
      out.write("			switch (status) {\r\n");
      out.write("			case 'operatorio':\r\n");
      out.write("				return {\r\n");
      out.write("					label : 'Pré-Operatório',\r\n");
      out.write("					cor : '#fbd972'\r\n");
      out.write("				};\r\n");
      out.write("			case 'sala-cirurgica':\r\n");
      out.write("				return {\r\n");
      out.write("					label : 'Em sala cirúrgica',\r\n");
      out.write("					cor : '#fd5766'\r\n");
      out.write("				};\r\n");
      out.write("			case 'recuperacao':\r\n");
      out.write("				return {\r\n");
      out.write("					label : 'Em recuperação',\r\n");
      out.write("					cor : '#89e89f'\r\n");
      out.write("				};\r\n");
      out.write("			case 'transferido':\r\n");
      out.write("				return {\r\n");
      out.write("					label : 'Transferído',\r\n");
      out.write("					cor : '#b8daff'\r\n");
      out.write("				};\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function atualizarTabela() {\r\n");
      out.write("			var tabela = \"\";\r\n");
      out.write("\r\n");
      out.write("			for (i in pacientes) {\r\n");
      out.write("				var stts = status(pacientes[i].status);\r\n");
      out.write("				tabela += '<tr onclick=\"preparaEdicao(' + i + ')\">' + '<td>'\r\n");
      out.write("						+ pacientes[i].nome + '</td>'\r\n");
      out.write("						+ '<td style=\"background-color: '+stts.cor+';\">'\r\n");
      out.write("						+ stts.label + pacientes[i].local + '</td>' + '<td>'\r\n");
      out.write("						+ pacientes[i].iniPrevisto + '</td>' + '<td>'\r\n");
      out.write("						+ pacientes[i].iniCirurgia + '</td>' + '<td>'\r\n");
      out.write("						+ pacientes[i].fimCirurgia + '</td>' + '<td>'\r\n");
      out.write("						+ pacientes[i].saidaPrev + '</td>' + '</tr>';\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			document.getElementById(\"corpo-tabela\").innerHTML = tabela;\r\n");
      out.write("			localStorage.setItem('corpo-tabela', tabela);\r\n");
      out.write("			localStorage.setItem('ls-tabela', JSON.stringify(pacientes));\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function limpaForm() {\r\n");
      out.write("			document.getElementById(\"id\").value = '';\r\n");
      out.write("			document.getElementById('form-paciente').reset();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function apagar() {\r\n");
      out.write("			var vId = document.getElementById(\"id\").value;\r\n");
      out.write("			if (vId != '') {\r\n");
      out.write("				var save = confirm(\"Tem certeza que quer apagar esse registro?\");\r\n");
      out.write("				if (save) {\r\n");
      out.write("					pacientes.splice(vId, 1);\r\n");
      out.write("					atualizarTabela();\r\n");
      out.write("					limpaForm();\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<br>\r\n");
      out.write("		<h2>Gerenciar Painel dos Paciente no Centro Cirúrgico</h2>\r\n");
      out.write("		<form name=\"form-paciente\" id=\"form-paciente\">\r\n");
      out.write("			<input type=\"hidden\" id=\"id\" name=\"id\">\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group col-md-6\">\r\n");
      out.write("					<label for=\"nome\">Nome Paciente:</label> <input type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"nome\" placeholder=\"Nome do Paciente\"\r\n");
      out.write("						name=\"nome\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group col-md-3\">\r\n");
      out.write("					<label for=\"nome\">Status:</label> <select name=\"status\" id=\"status\"\r\n");
      out.write("						class=\"form-control\">\r\n");
      out.write("						<option value=\"operatorio\">Pré-Operatório</option>\r\n");
      out.write("						<option value=\"sala-cirurgica\">Em sala cirúrgica</option>\r\n");
      out.write("						<option value=\"recuperacao\">Em recuperação</option>\r\n");
      out.write("						<option value=\"transferido\">Transferído</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group col-md-3\">\r\n");
      out.write("					<label for=\"local\">Local:</label> <input type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"local\" placeholder=\"Sala/Quarto\"\r\n");
      out.write("						name=\"local\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-row\">\r\n");
      out.write("				<div class=\"form-group  col-md-3\">\r\n");
      out.write("					<label for=\"inicio-previsto\">Início Prevísto:</label> <input\r\n");
      out.write("						type=\"time\" class=\"form-control\" id=\"inicio-previsto\"\r\n");
      out.write("						name=\"inicio-previsto\" size=\"20\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group  col-md-3\">\r\n");
      out.write("					<label for=\"inicio-previsto\">Início Cirurgia:</label> <input\r\n");
      out.write("						type=\"time\" class=\"form-control\" id=\"inicio-cirurgia\"\r\n");
      out.write("						name=\"inicio-previsto\" size=\"20\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group  col-md-3\">\r\n");
      out.write("					<label for=\"inicio-previsto\">Fim daCirurgia:</label> <input\r\n");
      out.write("						type=\"time\" class=\"form-control\" id=\"fim-cirurgia\"\r\n");
      out.write("						name=\"inicio-previsto\" size=\"20\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group  col-md-3\">\r\n");
      out.write("					<label for=\"inicio-previsto\">Saída Prevísto:</label> <input\r\n");
      out.write("						type=\"time\" class=\"form-control\" id=\"saida-previsto\"\r\n");
      out.write("						name=\"inicio-previsto\" size=\"20\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button type=\"button\" class=\"btn btn-secondary\" onclick=\"limpaForm()\">Novo</button>\r\n");
      out.write("			<button type=\"button\" class=\"btn btn-primary\" onclick=\"gravar(this)\">Gravar</button>\r\n");
      out.write("			<button type=\"button\" class=\"btn btn-danger\" onclick=\"apagar()\">Apagar</button>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<br>\r\n");
      out.write("		<table class=\"table table-hover\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"40%\">Nome do Paciente</th>\r\n");
      out.write("					<th width=\"30%\">Status</th>\r\n");
      out.write("					<th width=\"10%\">Início Prevísto</th>\r\n");
      out.write("					<th width=\"10%\">Início da Cirurgia</th>\r\n");
      out.write("					<th width=\"10%\">Fim da Cirurgia</th>\r\n");
      out.write("					<th width=\"10%\">Saída Prevista</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody id=\"corpo-tabela\" style=\"cursor: pointer;\">\r\n");
      out.write("\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			var tabela = localStorage.getItem('corpo-tabela');\r\n");
      out.write("			document.getElementById(\"corpo-tabela\").innerHTML = tabela;\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
