/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-13 21:44:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.cc.model.Usuario;
import java.io.PrintWriter;
import org.cc.model.Painel;
import org.cc.dao.PainelDao;
import java.util.List;
import org.cc.model.Usuario;
import org.cc.dao.UsuarioDao;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/formListaPainel.jsp", Long.valueOf(1631554941775L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1631030311270L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.cc.model.Painel");
    _jspx_imports_classes.add("org.cc.dao.PainelDao");
    _jspx_imports_classes.add("org.cc.model.Usuario");
    _jspx_imports_classes.add("org.cc.dao.UsuarioDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Painel Centro Cirúrgico</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/estilo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

        Usuario us = (Usuario) request.getSession().getAttribute("usuario");
    	if(us != null){ 
      out.write("\r\n");
      out.write("    		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#dadosUsuario{\r\n");
      out.write("	color: yellow;\r\n");
      out.write("	padding: 16px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("#dadosUsuario a{\r\n");
      out.write("	color: black;\r\n");
      out.write("	background-color:#fff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("	padding:2px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    font-size: 9px;\r\n");
      out.write("}\r\n");
      out.write("#dadosUsuario a:hover{\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	color: yellow;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<ul>\r\n");
      out.write("	  \r\n");
      out.write("	   ");

        Usuario usuario = (Usuario) request.getSession().getAttribute("usuario");
    	boolean verLista = false;
    	if(usuario != null){
    		verLista = true;
    	
      out.write("\r\n");
      out.write("    	<span id=\"dadosUsuario\"> <a href=\"loginservlet?acao=sair\"><b>Logout</b></a></span>\r\n");
      out.write("    	<span id=\"dadosUsuario\">Bem Vindo: ");
      out.print(usuario.getEmail());
      out.write("</span>\r\n");
      out.write("        <li><a href=\"index.jsp\"><b>Home</b></a></li>\r\n");
      out.write("        <li><a href=\"formGerenciaPainel.jsp\"><b>Gerenciar Painel</b></a>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(usuario.getPerfil().equals("administrador")){ 
      out.write("    \r\n");
      out.write("        <li><a href=\"formManterUsuario.jsp\"><b>Manter Usuário</b></a></li>\r\n");
      out.write("        ");
}else{
      out.write("\r\n");
      out.write("        <li><a href=\"formAlterarSenha.jsp\"><b>Alterar Senha</b></a></li>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("      ");

    	}else{
    	
      out.write("\r\n");
      out.write("   		<li></li>\r\n");
      out.write("    	");
	
    	} 
    	
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    	");
	} else { 
      out.write("\r\n");
      out.write("    		<span class=\"bt_direita\"><a href=\"formLogin.jsp\" >Acessar</a></span>\r\n");
      out.write("		");
	} 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<p>			\r\n");
      out.write("		<img\r\n");
      out.write("			src=\"img/Bandeira_do_Distrito_Federal_Brasil.png\" height=\"100px\">\r\n");
      out.write("		\r\n");
      out.write("		<script>\r\n");
      out.write("			var myVar = setInterval(myTimer, 1000);\r\n");
      out.write("			function myTimer() {\r\n");
      out.write("				var d = new Date();\r\n");
      out.write("				document.getElementById(\"dt-hora\").innerHTML = d.getDate()+'/'+(d.getMonth()+1)+'/'+d.getFullYear()+' '+ d\r\n");
      out.write("						.toLocaleTimeString();\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("		Hospital Regional de Taguatinga|Secretaria de Estado de Saúde do\r\n");
      out.write("		Distrito Federal| Pacientes no Centro Cirúgico - <span id=\"dt-hora\"></span>\r\n");
      out.write("		\r\n");
      out.write("	</p>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Listar Registros Painel</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/estilo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<h2>Painel do Centro Cirúrgico</h2>\r\n");
 
PrintWriter saida = response.getWriter();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"table table-success table-striped table-hover\">\r\n");
      out.write("	<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>Nome do Paciente</th>\r\n");
      out.write("			<th>Status</th>\r\n");
      out.write("			<th>Início Previsto</th>\r\n");
      out.write("			<th>Início Cirurgia</th>\r\n");
      out.write("			<th>Fim Cirurgia</th>\r\n");
      out.write("			<th>Saída Prevísta</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</thead>\r\n");
      out.write("		");

		PainelDao objPaiDao = new PainelDao();
		List<Painel> ls = objPaiDao.listarRegistrosPainel();

		if (ls.size() > 0) {
			for (Painel painel : ls) {
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<tr\r\n");
      out.write("			onclick=\"window.location.href = 'formGerenciaPainel.jsp?id=");
      out.print(painel.getId());
      out.write("'\">\r\n");
      out.write("			\r\n");
      out.write("			<td width=\"40%\">");
      out.print(painel.getNomePaciente());
      out.write("</td>\r\n");
      out.write("	\r\n");
      out.write("			");

			if(painel.getStatus().equals("operatorio")){
			
      out.write("	\r\n");
      out.write("				<td class=\"operatorio\" width=\"20%\">Pré-Operatório</td>\r\n");
      out.write("			");
				
			}else if(painel.getStatus().equals("sala-cirurgica")){
      out.write("\r\n");
      out.write("				<td class=\"salaCirurgia\" width=\"20%\">Em sala cirúrgica</td>\r\n");
      out.write("			");
 
			}else if(painel.getStatus().equals("recuperacao")){
      out.write("\r\n");
      out.write("				<td class=\"recuperacao\" width=\"20%\">Em recuperação</td>\r\n");
      out.write("			");
 
			}else if(painel.getStatus().equals("transferido")){
      out.write("\r\n");
      out.write("				<td class=\"transferido\" width=\"20%\">Transferido</td>\r\n");
      out.write("			");
	
			}else{
      out.write("\r\n");
      out.write("				<td width=\"20%\">");
      out.print(painel.getStatus());
      out.write("</td>\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<td width=\"10%\">");
      out.print(painel.getInicioPrevisto());
      out.write("</td>\r\n");
      out.write("			<td width=\"10%\">");
      out.print(painel.getInicioCirurgia());
      out.write("</td>\r\n");
      out.write("			<td width=\"10%\">");
      out.print(painel.getFimCirurgia());
      out.write("</td>\r\n");
      out.write("			<td width=\"10%\">");
      out.print(painel.getSaidaPrevista());
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"8\" style=\"text-align: center\">\"Nenhuma informação\r\n");
      out.write("				encontrada!\"</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
